version: "3.8"

services:
  app:
    container_name: core_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpass
      - DB_NAME=mydatabase
      - DB_PORT=5432 # Porta padrão do PostgreSQL
    depends_on:
      - db
    networks:
      - core_network

  db:
    container_name: core_database
    image: postgres:13 # Alterado para imagem do PostgreSQL
    restart: always
    ports:
      - "3315:5432" # Porta padrão do PostgreSQL é 5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      TZ: America/Sao_Paulo
    volumes:
      - db_data:/var/lib/postgresql/data # Persistência dos dados do PostgreSQL
    networks:
      - core_network # Conectando o serviço do banco de dados à rede

volumes:
  db_data:

networks:
  core_network:
