version: "3.8"

services:
  app:
    container_name: core_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=mydatabase
    depends_on:
      - db
    networks:
      - core_network

  db:
    container_name: core_database
    image: mysql:8.0
    restart: always
    ports:
      - "3315:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
      TZ: America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql # Persistência dos dados do MySQL
    networks:
      - core_network # Conectando o serviço do banco de dados à rede

volumes:
  db_data:

networks:
  core_network:
